// 4-letter words with clues for crossword puzzles
import type { WordClue } from "./types";

export const fourLetterWords: WordClue[] = [
  { word: "BOOK", clue: "Collection of pages to read" },
  { word: "TREE", clue: "Tall plant with a trunk" },
  { word: "FISH", clue: "Aquatic creature" },
  { word: "BIRD", clue: "Feathered flyer" },
  { word: "CAKE", clue: "Birthday dessert" },
  { word: "DOOR", clue: "Room entrance" },
  { word: "STAR", clue: "Twinkling night light" },
  { word: "MOON", clue: "Earth's satellite" },
  { word: "RAIN", clue: "Water from clouds" },
  { word: "WIND", clue: "Moving air" },
  { word: "SNOW", clue: "Frozen precipitation" },
  { word: "BOAT", clue: "Water vessel" },
  { word: "FROG", clue: "Amphibian that ribbits" },
  { word: "LION", clue: "King of the jungle" },
  { word: "BEAR", clue: "Large furry mammal" },
  { word: "WOLF", clue: "Howling canine" },
  { word: "DUCK", clue: "Quacking bird" },
  { word: "LAMP", clue: "Light source" },
  { word: "DESK", clue: "Work surface" },
  { word: "SOFA", clue: "Living room seating" },
  { word: "PLAY", clue: "Have fun" },
  { word: "JUMP", clue: "Leap in the air" },
  { word: "SWIM", clue: "Move through water" },
  { word: "COOK", clue: "Prepare food" },
  { word: "READ", clue: "Look at words" },
  { word: "WORK", clue: "Labor or employment" },
  { word: "BLUE", clue: "Color of the sky" },
  { word: "GOLD", clue: "Precious yellow metal" },
  { word: "PINK", clue: "Light red color" },
  { word: "GRAY", clue: "Color between black and white" },
  { word: "ARMY", clue: "Military force" },
  { word: "BAND", clue: "Musical group" },
  { word: "BELL", clue: "Ringing instrument" },
  { word: "BONE", clue: "Part of skeleton" },
  { word: "BOWL", clue: "Round dish" },
  { word: "CRAB", clue: "Sideways-walking crustacean" },
  { word: "DRUM", clue: "Percussion instrument" },
  { word: "FARM", clue: "Agricultural land" },
  { word: "FLAG", clue: "National symbol" },
  { word: "GAME", clue: "Fun activity" },
  { word: "GATE", clue: "Fence opening" },
  { word: "GIFT", clue: "Present" },
  { word: "HALL", clue: "Long corridor" },
  { word: "HAND", clue: "Body part with fingers" },
  { word: "HERO", clue: "Brave person" },
  { word: "HILL", clue: "Small mountain" },
  { word: "HOME", clue: "Where you live" },
  { word: "IRON", clue: "Metal or clothes presser" },
  { word: "JAIL", clue: "Prison" },
  { word: "KING", clue: "Male monarch" },
  { word: "LAKE", clue: "Inland body of water" },
  { word: "LEAF", clue: "Tree foliage" },
  { word: "LIME", clue: "Green citrus fruit" },
  { word: "MILK", clue: "White dairy drink" },
  { word: "NAIL", clue: "Metal fastener" },
  { word: "NEST", clue: "Bird's home" },
  { word: "NOSE", clue: "Smelling organ" },
  { word: "PALM", clue: "Tropical tree or hand part" },
  { word: "PARK", clue: "Green public space" },
  { word: "RING", clue: "Circular jewelry" },
  { word: "ROAD", clue: "Travel path" },
  { word: "ROCK", clue: "Stone" },
  { word: "ROOF", clue: "Building top" },
  { word: "ROPE", clue: "Thick cord" },
  { word: "ROSE", clue: "Thorny flower" },
  { word: "SALT", clue: "Table seasoning" },
  { word: "SAND", clue: "Beach grains" },
  { word: "SHIP", clue: "Large water vessel" },
  { word: "SHOP", clue: "Retail store" },
  { word: "SILK", clue: "Smooth fabric" },
  { word: "SKIN", clue: "Body covering" },
  { word: "SOAP", clue: "Cleaning bar" },
  { word: "SOCK", clue: "Foot covering" },
  { word: "SONG", clue: "Musical piece" },
  { word: "TANK", clue: "Military vehicle or container" },
  { word: "TENT", clue: "Camping shelter" },
  { word: "WALL", clue: "Room divider" },
  { word: "WAVE", clue: "Ocean movement" },
];
