// 5-letter words with clues for crossword puzzles
import type { WordClue } from "./types";

export const fiveLetterWords: WordClue[] = [
  { word: "APPLE", clue: "Red or green fruit" },
  { word: "BREAD", clue: "Baked grain product" },
  { word: "CHAIR", clue: "Furniture for sitting" },
  { word: "DREAM", clue: "Nighttime vision" },
  { word: "EAGLE", clue: "Majestic bird of prey" },
  { word: "FLAME", clue: "Fire's visible part" },
  { word: "GRAPE", clue: "Wine fruit" },
  { word: "HORSE", clue: "Galloping animal" },
  { word: "KNIFE", clue: "Cutting utensil" },
  { word: "LEMON", clue: "Sour yellow citrus" },
  { word: "MOUSE", clue: "Small rodent" },
  { word: "NIGHT", clue: "Time after sunset" },
  { word: "OCEAN", clue: "Large body of salt water" },
  { word: "PIANO", clue: "Keyboard instrument" },
  { word: "QUEEN", clue: "Female monarch" },
  { word: "RIVER", clue: "Flowing water body" },
  { word: "STORM", clue: "Violent weather" },
  { word: "TIGER", clue: "Striped big cat" },
  { word: "WATER", clue: "H2O" },
  { word: "ZEBRA", clue: "Striped African animal" },
  { word: "BEACH", clue: "Sandy shore" },
  { word: "CLOUD", clue: "Fluffy sky formation" },
  { word: "DRINK", clue: "Consume liquid" },
  { word: "EARTH", clue: "Our planet" },
  { word: "FLOOR", clue: "Walking surface" },
  { word: "GLASS", clue: "Transparent material" },
  { word: "HOUSE", clue: "Place to live" },
  { word: "JUICE", clue: "Fruit drink" },
  { word: "MONEY", clue: "Currency" },
  { word: "PLANT", clue: "Green growing thing" },
  { word: "ANGEL", clue: "Heavenly being" },
  { word: "BACON", clue: "Breakfast meat" },
  { word: "BEARD", clue: "Facial hair" },
  { word: "BLACK", clue: "Darkest color" },
  { word: "BLANK", clue: "Empty space" },
  { word: "BRAIN", clue: "Thinking organ" },
  { word: "BRICK", clue: "Building block" },
  { word: "CANDY", clue: "Sweet treat" },
  { word: "CHAIN", clue: "Linked metal" },
  { word: "CHALK", clue: "Writing stick for boards" },
  { word: "CHEST", clue: "Storage box or body part" },
  { word: "CHILD", clue: "Young person" },
  { word: "CLOCK", clue: "Time-telling device" },
  { word: "COAST", clue: "Shoreline" },
  { word: "CORAL", clue: "Ocean reef material" },
  { word: "COUCH", clue: "Living room seat" },
  { word: "CREAM", clue: "Dairy topping" },
  { word: "CROWN", clue: "Royal headwear" },
  { word: "DANCE", clue: "Move to music" },
  { word: "DEATH", clue: "End of life" },
  { word: "DEPTH", clue: "How deep" },
  { word: "DOUGH", clue: "Bread mixture" },
  { word: "ELBOW", clue: "Arm joint" },
  { word: "EMPTY", clue: "Nothing inside" },
  { word: "FAIRY", clue: "Magical winged creature" },
  { word: "FEAST", clue: "Large meal" },
  { word: "FENCE", clue: "Yard barrier" },
  { word: "FEVER", clue: "High body temperature" },
  { word: "FIELD", clue: "Open grassy area" },
  { word: "FRUIT", clue: "Sweet plant product" },
  { word: "GIANT", clue: "Very large being" },
  { word: "GLOBE", clue: "Earth model" },
  { word: "GOOSE", clue: "Honking bird" },
  { word: "GRAIN", clue: "Cereal crop" },
  { word: "GRASS", clue: "Lawn covering" },
  { word: "GREEN", clue: "Color of leaves" },
  { word: "HEART", clue: "Blood-pumping organ" },
  { word: "HONEY", clue: "Bee product" },
  { word: "HOTEL", clue: "Traveler's lodging" },
  { word: "JELLY", clue: "Wobbly spread" },
  { word: "LABEL", clue: "Identifying tag" },
  { word: "LASER", clue: "Focused light beam" },
  { word: "LAYER", clue: "One thickness" },
  { word: "LIGHT", clue: "Illumination" },
  { word: "LUNCH", clue: "Midday meal" },
  { word: "MAGIC", clue: "Supernatural power" },
  { word: "MAPLE", clue: "Syrup tree" },
  { word: "MATCH", clue: "Fire starter" },
  { word: "MELON", clue: "Large sweet fruit" },
  { word: "METAL", clue: "Iron or steel" },
  { word: "MUSIC", clue: "Melodic sounds" },
  { word: "NORTH", clue: "Compass direction" },
  { word: "ONION", clue: "Tear-inducing vegetable" },
  { word: "PAINT", clue: "Wall coloring" },
  { word: "PAPER", clue: "Writing material" },
  { word: "PARTY", clue: "Celebration" },
  { word: "PEACE", clue: "Absence of war" },
  { word: "PEARL", clue: "Oyster gem" },
  { word: "PHONE", clue: "Communication device" },
  { word: "PIZZA", clue: "Italian pie" },
  { word: "PLATE", clue: "Dinner dish" },
  { word: "PRIZE", clue: "Award" },
  { word: "PROOF", clue: "Evidence" },
  { word: "PUPPY", clue: "Baby dog" },
  { word: "RADIO", clue: "Broadcast receiver" },
  { word: "ROBIN", clue: "Red-breasted bird" },
  { word: "SALAD", clue: "Leafy dish" },
  { word: "SCALE", clue: "Weighing device" },
  { word: "SHARK", clue: "Ocean predator" },
  { word: "SHEEP", clue: "Woolly animal" },
  { word: "SHELL", clue: "Hard outer covering" },
  { word: "SHIRT", clue: "Upper body garment" },
  { word: "SKIRT", clue: "Lower body garment" },
  { word: "SLEEP", clue: "Nightly rest" },
  { word: "SLIDE", clue: "Playground equipment" },
  { word: "SMILE", clue: "Happy expression" },
  { word: "SMOKE", clue: "Fire byproduct" },
  { word: "SNAKE", clue: "Legless reptile" },
  { word: "SOUND", clue: "What you hear" },
  { word: "SOUTH", clue: "Opposite of north" },
  { word: "SPACE", clue: "Outer cosmos" },
  { word: "SPOON", clue: "Eating utensil" },
  { word: "STAMP", clue: "Mail marking" },
  { word: "STONE", clue: "Rock" },
  { word: "STORE", clue: "Shopping place" },
  { word: "STOVE", clue: "Cooking appliance" },
  { word: "SUGAR", clue: "Sweet substance" },
  { word: "SWING", clue: "Playground seat" },
  { word: "SWORD", clue: "Medieval weapon" },
  { word: "TABLE", clue: "Dining furniture" },
  { word: "TEETH", clue: "Mouth bones" },
  { word: "THUMB", clue: "Opposable digit" },
  { word: "TOAST", clue: "Browned bread" },
  { word: "TOOTH", clue: "Mouth bone" },
  { word: "TORCH", clue: "Handheld flame" },
  { word: "TOWER", clue: "Tall structure" },
  { word: "TRACK", clue: "Running path" },
  { word: "TRAIN", clue: "Rail transport" },
  { word: "TRASH", clue: "Garbage" },
  { word: "TRUCK", clue: "Large vehicle" },
  { word: "TRUNK", clue: "Tree base or car storage" },
  { word: "VOICE", clue: "Speaking sound" },
  { word: "WATCH", clue: "Wrist timepiece" },
  { word: "WHALE", clue: "Largest mammal" },
  { word: "WHEAT", clue: "Bread grain" },
  { word: "WHEEL", clue: "Circular roller" },
  { word: "WHITE", clue: "Snow color" },
  { word: "WITCH", clue: "Magic woman" },
  { word: "WOMAN", clue: "Adult female" },
  { word: "WORLD", clue: "The Earth" },
  { word: "WRIST", clue: "Hand-arm joint" },
  { word: "YOUTH", clue: "Young age" },
];
