// 6-letter words with clues for crossword puzzles
import type { WordClue } from "./types";

export const sixLetterWords: WordClue[] = [
  { word: "ANIMAL", clue: "Living creature" },
  { word: "BANANA", clue: "Yellow tropical fruit" },
  { word: "CAMERA", clue: "Photo-taking device" },
  { word: "DESERT", clue: "Dry sandy region" },
  { word: "ENGINE", clue: "Power source" },
  { word: "FLOWER", clue: "Blooming plant part" },
  { word: "GARDEN", clue: "Plant growing area" },
  { word: "HAMMER", clue: "Nail-driving tool" },
  { word: "ISLAND", clue: "Land surrounded by water" },
  { word: "JUNGLE", clue: "Dense tropical forest" },
  { word: "KITTEN", clue: "Baby cat" },
  { word: "LADDER", clue: "Climbing device" },
  { word: "MARKET", clue: "Place to buy goods" },
  { word: "ORANGE", clue: "Citrus fruit" },
  { word: "PARADE", clue: "Festive procession" },
  { word: "RABBIT", clue: "Hopping animal with long ears" },
  { word: "SCHOOL", clue: "Learning institution" },
  { word: "TURTLE", clue: "Slow shelled reptile" },
  { word: "WINTER", clue: "Cold season" },
  { word: "YELLOW", clue: "Color of the sun" },
  { word: "BRIDGE", clue: "River crossing structure" },
  { word: "CASTLE", clue: "Royal fortress" },
  { word: "DOCTOR", clue: "Medical professional" },
  { word: "FOREST", clue: "Area of many trees" },
  { word: "INSECT", clue: "Six-legged creature" },
  { word: "JACKET", clue: "Outer garment" },
  { word: "PLANET", clue: "Celestial body" },
  { word: "ROCKET", clue: "Space vehicle" },
  { word: "SPIDER", clue: "Eight-legged crawler" },
  { word: "SUMMER", clue: "Warm season" },
  { word: "ANCHOR", clue: "Ship stopper" },
  { word: "ARTIST", clue: "Creative person" },
  { word: "AUTUMN", clue: "Fall season" },
  { word: "BAKERY", clue: "Bread shop" },
  { word: "BASKET", clue: "Carrying container" },
  { word: "BATTLE", clue: "Military fight" },
  { word: "BEAUTY", clue: "Attractiveness" },
  { word: "BEETLE", clue: "Hard-shelled insect" },
  { word: "BORDER", clue: "Country edge" },
  { word: "BOTTLE", clue: "Liquid container" },
  { word: "BRANCH", clue: "Tree limb" },
  { word: "BRONZE", clue: "Third place metal" },
  { word: "BUBBLE", clue: "Soap sphere" },
  { word: "BUCKET", clue: "Water carrier" },
  { word: "BUTTER", clue: "Bread spread" },
  { word: "BUTTON", clue: "Shirt fastener" },
  { word: "CANDLE", clue: "Wax light" },
  { word: "CARPET", clue: "Floor covering" },
  { word: "CARROT", clue: "Orange vegetable" },
  { word: "CHEESE", clue: "Dairy product" },
  { word: "CHERRY", clue: "Small red fruit" },
  { word: "CHURCH", clue: "Place of worship" },
  { word: "CIRCLE", clue: "Round shape" },
  { word: "CLOSET", clue: "Clothes storage" },
  { word: "COFFEE", clue: "Morning beverage" },
  { word: "COOKIE", clue: "Sweet baked treat" },
  { word: "COPPER", clue: "Reddish metal" },
  { word: "CORNER", clue: "Where walls meet" },
  { word: "COTTON", clue: "Soft fabric" },
  { word: "COUSIN", clue: "Relative" },
  { word: "CRAYON", clue: "Wax coloring stick" },
  { word: "CRUISE", clue: "Ocean voyage" },
  { word: "DANCER", clue: "Movement performer" },
  { word: "DANGER", clue: "Risk" },
  { word: "DINNER", clue: "Evening meal" },
  { word: "DONKEY", clue: "Stubborn animal" },
  { word: "DRAGON", clue: "Fire-breathing creature" },
  { word: "DRAWER", clue: "Sliding storage" },
  { word: "DRIVER", clue: "Car operator" },
  { word: "EMPIRE", clue: "Large kingdom" },
  { word: "ENERGY", clue: "Power source" },
  { word: "ESCAPE", clue: "Get away" },
  { word: "FABRIC", clue: "Cloth material" },
  { word: "FAMILY", clue: "Related group" },
  { word: "FARMER", clue: "Crop grower" },
  { word: "FATHER", clue: "Male parent" },
  { word: "FINGER", clue: "Hand digit" },
  { word: "FROZEN", clue: "Very cold" },
  { word: "GARAGE", clue: "Car storage" },
  { word: "GINGER", clue: "Spicy root" },
  { word: "GLOBAL", clue: "Worldwide" },
  { word: "GOBLET", clue: "Fancy cup" },
  { word: "GUITAR", clue: "String instrument" },
  { word: "HARBOR", clue: "Boat shelter" },
  { word: "HELMET", clue: "Head protector" },
  { word: "HIKER", clue: "Trail walker" },
  { word: "HOLDER", clue: "Container" },
  { word: "HONEST", clue: "Truthful" },
  { word: "HUNGRY", clue: "Wanting food" },
  { word: "HUNTER", clue: "Animal tracker" },
  { word: "JIGSAW", clue: "Puzzle type" },
  { word: "KEEPER", clue: "Guardian" },
  { word: "KERNEL", clue: "Corn piece" },
  { word: "KETTLE", clue: "Water boiler" },
  { word: "KNIGHT", clue: "Armored warrior" },
  { word: "LAWYER", clue: "Legal professional" },
  { word: "LEADER", clue: "Person in charge" },
  { word: "LEGEND", clue: "Famous story" },
  { word: "LETTER", clue: "Written message" },
  { word: "LIQUID", clue: "Flowing substance" },
  { word: "LIZARD", clue: "Small reptile" },
  { word: "LOCKER", clue: "Storage compartment" },
  { word: "MAGNET", clue: "Iron attractor" },
  { word: "MIRROR", clue: "Reflection surface" },
  { word: "MONKEY", clue: "Climbing primate" },
  { word: "MOTHER", clue: "Female parent" },
  { word: "MUSEUM", clue: "Art building" },
  { word: "NAPKIN", clue: "Dinner cloth" },
  { word: "NATURE", clue: "The outdoors" },
  { word: "NEEDLE", clue: "Sewing tool" },
  { word: "NEPHEW", clue: "Sibling's son" },
  { word: "NOODLE", clue: "Pasta strand" },
  { word: "NUMBER", clue: "Math symbol" },
  { word: "OFFICE", clue: "Work place" },
  { word: "ORCHID", clue: "Exotic flower" },
  { word: "OYSTER", clue: "Pearl producer" },
  { word: "PADDLE", clue: "Canoe mover" },
  { word: "PALACE", clue: "Royal home" },
  { word: "PANDA", clue: "Black and white bear" },
  { word: "PARROT", clue: "Talking bird" },
  { word: "PASTRY", clue: "Baked goods" },
  { word: "PEANUT", clue: "Legume snack" },
  { word: "PEPPER", clue: "Spicy seasoning" },
  { word: "PERSON", clue: "Human being" },
  { word: "PIRATE", clue: "Sea robber" },
  { word: "POCKET", clue: "Pants pouch" },
  { word: "POISON", clue: "Toxic substance" },
  { word: "POLICE", clue: "Law enforcement" },
  { word: "POTATO", clue: "Starchy vegetable" },
  { word: "PRINCE", clue: "King's son" },
  { word: "PRISON", clue: "Jail" },
  { word: "PUZZLE", clue: "Brain teaser" },
  { word: "QUARTZ", clue: "Crystal mineral" },
  { word: "RADISH", clue: "Red root vegetable" },
  { word: "RECIPE", clue: "Cooking instructions" },
  { word: "RECORD", clue: "Music disc" },
  { word: "REFUGE", clue: "Safe place" },
  { word: "RIBBON", clue: "Decorative strip" },
  { word: "RUNNER", clue: "Jogging person" },
  { word: "SADDLE", clue: "Horse seat" },
  { word: "SAILOR", clue: "Ship worker" },
  { word: "SALMON", clue: "Pink fish" },
  { word: "SAMPLE", clue: "Test piece" },
  { word: "SCARCE", clue: "Rare" },
  { word: "SECRET", clue: "Hidden info" },
  { word: "SHADOW", clue: "Dark shape" },
  { word: "SHIELD", clue: "Protective barrier" },
  { word: "SILVER", clue: "Shiny metal" },
  { word: "SINGER", clue: "Vocal performer" },
  { word: "SISTER", clue: "Female sibling" },
  { word: "SOCKET", clue: "Electrical outlet" },
  { word: "SOLDIER", clue: "Military person" },
  { word: "SPRING", clue: "Bouncy season" },
  { word: "SQUARE", clue: "Four-sided shape" },
  { word: "STABLE", clue: "Horse house" },
  { word: "STATUE", clue: "Stone sculpture" },
  { word: "STREAM", clue: "Small river" },
  { word: "STREET", clue: "City road" },
  { word: "STRING", clue: "Thin cord" },
  { word: "SUNSET", clue: "Evening sky" },
  { word: "SWITCH", clue: "On/off control" },
  { word: "SYSTEM", clue: "Organized method" },
  { word: "TARGET", clue: "Aim point" },
  { word: "TEAPOT", clue: "Hot drink vessel" },
  { word: "TEMPLE", clue: "Holy building" },
  { word: "THREAD", clue: "Sewing fiber" },
  { word: "THROAT", clue: "Neck passage" },
  { word: "THRONE", clue: "King's seat" },
  { word: "TICKET", clue: "Entry pass" },
  { word: "TOMATO", clue: "Red salad fruit" },
  { word: "TONGUE", clue: "Taste organ" },
  { word: "TRAVEL", clue: "Journey" },
  { word: "TROPHY", clue: "Winner's prize" },
  { word: "TUNNEL", clue: "Underground passage" },
  { word: "TURKEY", clue: "Thanksgiving bird" },
  { word: "VALLEY", clue: "Low land between hills" },
  { word: "VELVET", clue: "Soft fabric" },
  { word: "VIOLIN", clue: "String instrument" },
  { word: "WALLET", clue: "Money holder" },
  { word: "WALNUT", clue: "Tree nut" },
  { word: "WAITER", clue: "Restaurant server" },
  { word: "WEAPON", clue: "Fighting tool" },
  { word: "WINDOW", clue: "Glass opening" },
  { word: "WIZARD", clue: "Magic man" },
  { word: "WONDER", clue: "Amazement" },
  { word: "WREATH", clue: "Door decoration" },
  { word: "WRITER", clue: "Author" },
  { word: "YOGURT", clue: "Dairy snack" },
  { word: "ZIPPER", clue: "Jacket fastener" },
];
