// 3-letter words with clues for crossword puzzles
import type { WordClue } from "./types";

export const threeLetterWords: WordClue[] = [
  { word: "CAT", clue: "Feline pet" },
  { word: "DOG", clue: "Man's best friend" },
  { word: "SUN", clue: "Star at center of our solar system" },
  { word: "RUN", clue: "Move quickly on foot" },
  { word: "FUN", clue: "Enjoyment or amusement" },
  { word: "BAT", clue: "Flying nocturnal mammal" },
  { word: "HAT", clue: "Head covering" },
  { word: "MAP", clue: "Geographic chart" },
  { word: "CUP", clue: "Drinking vessel" },
  { word: "BUS", clue: "Public transport vehicle" },
  { word: "OWL", clue: "Wise nocturnal bird" },
  { word: "ANT", clue: "Tiny insect in a colony" },
  { word: "BEE", clue: "Honey maker" },
  { word: "ICE", clue: "Frozen water" },
  { word: "SKY", clue: "Where clouds float" },
  { word: "PEN", clue: "Writing instrument" },
  { word: "JAM", clue: "Fruit preserve" },
  { word: "EGG", clue: "Breakfast staple from a hen" },
  { word: "KEY", clue: "Opens a lock" },
  { word: "NET", clue: "Fishing or tennis equipment" },
  { word: "BOX", clue: "Container with sides" },
  { word: "FOX", clue: "Clever red animal" },
  { word: "GYM", clue: "Place to exercise" },
  { word: "JOB", clue: "Employment position" },
  { word: "RED", clue: "Color of roses" },
  { word: "BIG", clue: "Large in size" },
  { word: "OLD", clue: "Not young" },
  { word: "NEW", clue: "Recently made" },
  { word: "HOT", clue: "High temperature" },
  { word: "WET", clue: "Covered in water" },
  { word: "ARM", clue: "Body limb" },
  { word: "LEG", clue: "Walking limb" },
  { word: "EAR", clue: "Hearing organ" },
  { word: "EYE", clue: "Seeing organ" },
  { word: "PIE", clue: "Baked pastry dessert" },
  { word: "TEA", clue: "Hot beverage from leaves" },
  { word: "COW", clue: "Milk-producing farm animal" },
  { word: "PIG", clue: "Farm animal that oinks" },
  { word: "HEN", clue: "Female chicken" },
  { word: "RAT", clue: "Long-tailed rodent" },
  { word: "WAR", clue: "Armed conflict" },
  { word: "DAY", clue: "24-hour period" },
  { word: "AIR", clue: "What we breathe" },
  { word: "OAK", clue: "Strong hardwood tree" },
  { word: "JAR", clue: "Glass container" },
  { word: "INK", clue: "Pen fluid" },
  { word: "OIL", clue: "Cooking or lubricating liquid" },
  { word: "GAS", clue: "Fuel for cars" },
  { word: "SEA", clue: "Saltwater body" },
  { word: "BAY", clue: "Coastal inlet" },
  { word: "ROW", clue: "Line of items" },
  { word: "TOY", clue: "Child's plaything" },
  { word: "BOY", clue: "Young male" },
  { word: "MAN", clue: "Adult male" },
  { word: "SON", clue: "Male offspring" },
  { word: "DAD", clue: "Father informally" },
  { word: "MOM", clue: "Mother informally" },
  { word: "BED", clue: "Sleeping furniture" },
  // Additional 3-letter words
  { word: "ACE", clue: "Top card" },
  { word: "ADD", clue: "Sum up" },
  { word: "AGE", clue: "How old" },
  { word: "AID", clue: "Help" },
  { word: "AIM", clue: "Target" },
  { word: "ALE", clue: "Beer type" },
  { word: "APE", clue: "Large primate" },
  { word: "ARC", clue: "Curved line" },
  { word: "ARK", clue: "Noah's boat" },
  { word: "ART", clue: "Creative work" },
  { word: "ATE", clue: "Past tense of eat" },
  { word: "AWE", clue: "Wonder" },
  { word: "AXE", clue: "Chopping tool" },
  { word: "BAG", clue: "Carrying sack" },
  { word: "BAN", clue: "Prohibition" },
  { word: "BAR", clue: "Drinking establishment" },
  { word: "BIT", clue: "Small piece" },
  { word: "BOW", clue: "Archer's weapon" },
  { word: "BUD", clue: "Flower beginning" },
  { word: "BUG", clue: "Small insect" },
  { word: "BUN", clue: "Bread roll" },
  { word: "CAB", clue: "Taxi" },
  { word: "CAP", clue: "Baseball hat" },
  { word: "COB", clue: "Corn core" },
  { word: "COD", clue: "White fish" },
  { word: "CUB", clue: "Baby bear" },
  { word: "CUT", clue: "Slice" },
  { word: "DAM", clue: "Water barrier" },
  { word: "DEN", clue: "Animal's lair" },
  { word: "DEW", clue: "Morning moisture" },
  { word: "DIG", clue: "Excavate" },
  { word: "DIM", clue: "Not bright" },
  { word: "DIP", clue: "Quick swim" },
  { word: "DOT", clue: "Small spot" },
  { word: "DRY", clue: "Not wet" },
  { word: "DUE", clue: "Owed" },
  { word: "DUG", clue: "Excavated" },
  { word: "EAT", clue: "Consume food" },
  { word: "EEL", clue: "Slippery fish" },
  { word: "ELF", clue: "Santa's helper" },
  { word: "ELM", clue: "Shade tree" },
  { word: "END", clue: "Finish" },
  { word: "ERA", clue: "Time period" },
  { word: "EVE", clue: "Night before" },
  { word: "FAD", clue: "Passing trend" },
  { word: "FAN", clue: "Cooling device" },
  { word: "FAR", clue: "Distant" },
  { word: "FAT", clue: "Not thin" },
  { word: "FAX", clue: "Office machine" },
  { word: "FED", clue: "Given food" },
  { word: "FEW", clue: "Not many" },
  { word: "FIG", clue: "Sweet fruit" },
  { word: "FIN", clue: "Fish's flipper" },
  { word: "FIT", clue: "In good shape" },
  { word: "FLY", clue: "Buzzing insect" },
  { word: "FOE", clue: "Enemy" },
  { word: "FOG", clue: "Thick mist" },
  { word: "FUR", clue: "Animal coat" },
  { word: "GAP", clue: "Opening" },
  { word: "GEL", clue: "Hair product" },
  { word: "GEM", clue: "Precious stone" },
  { word: "GOD", clue: "Deity" },
  { word: "GOT", clue: "Received" },
  { word: "GUM", clue: "Chewing candy" },
  { word: "GUN", clue: "Firearm" },
  { word: "GUT", clue: "Stomach" },
  { word: "HAM", clue: "Pork cut" },
  { word: "HIP", clue: "Body joint" },
  { word: "HIT", clue: "Strike" },
  { word: "HOG", clue: "Pig" },
  { word: "HOP", clue: "Small jump" },
  { word: "HUB", clue: "Center point" },
  { word: "HUG", clue: "Embrace" },
  { word: "HUM", clue: "Sing without words" },
  { word: "HUT", clue: "Small shelter" },
  { word: "INN", clue: "Small hotel" },
  { word: "IVY", clue: "Climbing plant" },
  { word: "JET", clue: "Fast plane" },
  { word: "JOG", clue: "Slow run" },
  { word: "JOY", clue: "Happiness" },
  { word: "JUG", clue: "Liquid pitcher" },
  { word: "KIT", clue: "Set of tools" },
  { word: "LAB", clue: "Science room" },
  { word: "LAP", clue: "Sitting area" },
  { word: "LAW", clue: "Legal rule" },
  { word: "LAY", clue: "Put down" },
  { word: "LID", clue: "Cover" },
  { word: "LIE", clue: "Untruth" },
  { word: "LIP", clue: "Mouth edge" },
  { word: "LOG", clue: "Wood piece" },
  { word: "LOT", clue: "Many" },
  { word: "LOW", clue: "Not high" },
  { word: "MAD", clue: "Angry" },
  { word: "MAT", clue: "Floor pad" },
  { word: "MAX", clue: "Maximum" },
  { word: "MAY", clue: "Spring month" },
  { word: "MET", clue: "Encountered" },
  { word: "MIX", clue: "Blend" },
  { word: "MOB", clue: "Crowd" },
  { word: "MOP", clue: "Floor cleaner" },
  { word: "MUD", clue: "Wet dirt" },
  { word: "MUG", clue: "Coffee cup" },
  { word: "NAP", clue: "Short sleep" },
  { word: "NIT", clue: "Lice egg" },
  { word: "NOD", clue: "Head gesture" },
  { word: "NOR", clue: "Neither's partner" },
  { word: "NOT", clue: "Negation" },
  { word: "NUN", clue: "Religious woman" },
  { word: "NUT", clue: "Tree seed" },
  { word: "OAR", clue: "Rowing tool" },
  { word: "OAT", clue: "Cereal grain" },
  { word: "ODD", clue: "Strange" },
  { word: "ORB", clue: "Sphere" },
  { word: "ORE", clue: "Metal rock" },
  { word: "OUR", clue: "Belonging to us" },
  { word: "OUT", clue: "Not in" },
  { word: "OWE", clue: "Be in debt" },
  { word: "OWN", clue: "Possess" },
  { word: "PAD", clue: "Cushion" },
  { word: "PAN", clue: "Cooking pot" },
  { word: "PAT", clue: "Gentle touch" },
  { word: "PAW", clue: "Animal foot" },
  { word: "PAY", clue: "Give money" },
  { word: "PEA", clue: "Green vegetable" },
  { word: "PET", clue: "Companion animal" },
  { word: "PIN", clue: "Sewing fastener" },
  { word: "PIT", clue: "Hole" },
  { word: "POD", clue: "Pea holder" },
  { word: "POP", clue: "Soda" },
  { word: "POT", clue: "Cooking vessel" },
  { word: "PRY", clue: "Force open" },
  { word: "PUB", clue: "British bar" },
  { word: "PUN", clue: "Word joke" },
  { word: "PUP", clue: "Young dog" },
  { word: "PUT", clue: "Place" },
  { word: "RAG", clue: "Old cloth" },
  { word: "RAM", clue: "Male sheep" },
  { word: "RAN", clue: "Past of run" },
  { word: "RAP", clue: "Music genre" },
  { word: "RAW", clue: "Uncooked" },
  { word: "RAY", clue: "Light beam" },
  { word: "RIB", clue: "Chest bone" },
  { word: "RID", clue: "Remove" },
  { word: "RIG", clue: "Equipment setup" },
  { word: "RIM", clue: "Edge" },
  { word: "RIP", clue: "Tear" },
  { word: "ROB", clue: "Steal from" },
  { word: "ROD", clue: "Fishing pole" },
  { word: "ROT", clue: "Decay" },
  { word: "RUB", clue: "Massage" },
  { word: "RUG", clue: "Floor mat" },
  { word: "RUM", clue: "Pirate's drink" },
  { word: "SAC", clue: "Pouch" },
  { word: "SAD", clue: "Unhappy" },
  { word: "SAG", clue: "Droop" },
  { word: "SAP", clue: "Tree fluid" },
  { word: "SAT", clue: "Past of sit" },
  { word: "SAW", clue: "Cutting tool" },
  { word: "SAY", clue: "Speak" },
  { word: "SET", clue: "Group" },
  { word: "SEW", clue: "Stitch" },
  { word: "SHY", clue: "Timid" },
  { word: "SIN", clue: "Wrongdoing" },
  { word: "SIP", clue: "Small drink" },
  { word: "SIT", clue: "Take a seat" },
  { word: "SIX", clue: "After five" },
  { word: "SKI", clue: "Snow sport" },
  { word: "SLY", clue: "Cunning" },
  { word: "SOB", clue: "Cry hard" },
  { word: "SOD", clue: "Grass layer" },
  { word: "SOP", clue: "Soak up" },
  { word: "SOW", clue: "Plant seeds" },
  { word: "SOY", clue: "Bean type" },
  { word: "SPA", clue: "Health resort" },
  { word: "SPY", clue: "Secret agent" },
  { word: "STY", clue: "Pig pen" },
  { word: "SUB", clue: "Submarine" },
  { word: "SUM", clue: "Total" },
  { word: "TAB", clue: "Bill" },
  { word: "TAG", clue: "Label" },
  { word: "TAN", clue: "Sun color" },
  { word: "TAP", clue: "Light touch" },
  { word: "TAR", clue: "Road material" },
  { word: "TAX", clue: "Government fee" },
  { word: "TEN", clue: "After nine" },
  { word: "THE", clue: "Common article" },
  { word: "TIE", clue: "Neck wear" },
  { word: "TIN", clue: "Metal container" },
  { word: "TIP", clue: "Gratuity" },
  { word: "TOE", clue: "Foot digit" },
  { word: "TON", clue: "Heavy weight" },
  { word: "TOP", clue: "Highest point" },
  { word: "TOW", clue: "Pull along" },
  { word: "TRY", clue: "Attempt" },
  { word: "TUB", clue: "Bath container" },
  { word: "TUG", clue: "Pull hard" },
  { word: "TWO", clue: "After one" },
  { word: "URN", clue: "Decorative vase" },
  { word: "USE", clue: "Utilize" },
  { word: "VAN", clue: "Cargo vehicle" },
  { word: "VAT", clue: "Large container" },
  { word: "VET", clue: "Animal doctor" },
  { word: "VIA", clue: "By way of" },
  { word: "VIE", clue: "Compete" },
  { word: "VOW", clue: "Promise" },
  { word: "WAD", clue: "Lump" },
  { word: "WAG", clue: "Tail movement" },
  { word: "WAS", clue: "Past of is" },
  { word: "WAX", clue: "Candle material" },
  { word: "WAY", clue: "Path" },
  { word: "WEB", clue: "Spider's home" },
  { word: "WED", clue: "Marry" },
  { word: "WIG", clue: "False hair" },
  { word: "WIN", clue: "Victory" },
  { word: "WIT", clue: "Humor" },
  { word: "WOE", clue: "Sorrow" },
  { word: "WOK", clue: "Asian pan" },
  { word: "WON", clue: "Past of win" },
  { word: "WOO", clue: "Court romantically" },
  { word: "YAM", clue: "Sweet potato" },
  { word: "YAP", clue: "Small bark" },
  { word: "YAW", clue: "Ship's turn" },
  { word: "YEN", clue: "Japanese currency" },
  { word: "YES", clue: "Affirmative" },
  { word: "YET", clue: "Still" },
  { word: "YEW", clue: "Evergreen tree" },
  { word: "ZAP", clue: "Zap with energy" },
  { word: "ZEN", clue: "Meditation practice" },
  { word: "ZIP", clue: "Fast movement" },
  { word: "ZIT", clue: "Pimple" },
  { word: "ZOO", clue: "Animal park" },
];
